AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  technical-test

Globals:
  Function:
    Timeout: 3

Resources:
  GetNameAndCurrentTime:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-name-and-current-time/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HttpApi:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  GetNameAndCurrentTimeApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
